version: '3.8'

services:
  camera:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /run/udev:/run/udev:ro
    ports:
      - "8554:8554"  # RTSP port
    restart: always
    privileged: true
