version: '3.8'

services:
  camera:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /run/udev:/run/udev:ro
    ports:
      - "8011:8011"
    restart: always
    privileged: true
